# (1)
par(mai = c(1, 1, 1, 1), omi = c(0, 0, 0, 0))
# (2)
yy <- c(50,30,40)
# (3)
name1 <- c("data-a", "data-b", "data-c")
# (4)
pie(yy, labels = name1, col = c("red","green","skyblue"))
# (5)
par(new = T)
# (6)
par(mai=c(2, 2, 2, 2))
# (7)
yy2 <- c(50, 20, 10, 20, 20)
# (8)
name2 <- c("data-a1", "data-b1", "data-b2", "data-c1", 
           "data-c2")
# (9)
pie(yy2, labels = name2, col = c("pink", "gold", "blue", 
                                 "gold", "blue"))